### ISSUE TITLE
Naemon segfault when wrong localhostgroups value

### ISSUE THREAD

**Issue by topinet** [sni/mod_gearman#100]
If localhostgroups defines a non-existent group, Naemon crashes while initializing mod-gearman module but module logfile only output a INFO message:
  Warning: hostgroup '"XXXXXXXXXX"' does not exist, possible typo?

Tested in latests versions (Naemon 1.0.5 with mod_gearman 3.0.0b1 and 3.0.0b2)

**Comment by sni** [comment]
Thanks, should be fixed now.
