### ISSUE TITLE
gearmand issues "Too many open files" in combination with mod-gearman

### ISSUE THREAD

**Issue by p-alik** [sni/mod_gearman#105]
There are some issues in gearmand community refer to combination of gearmand and mod-gearman:
 
- [memory leak](https://github.com/gearman/gearmand/issues/7)
- [to many fd files](https://groups.google.com/d/msg/gearman/AxkDVxIxMj0/mWdLiXAmCQAJ)

From the behaviour described there it could be an mod-gearman issue. For instance if mod-gearman does not close network connection to gearmand and gearmad has to wait until connection timed out.

**Comment by sni** [comment]
Regarding the memory leak we still use gearmand 0.33 in production and never had any issues with that.
The open files would be interesting to know if there is a leak, which means the open files would constantly grow, or if there are just many in use. Each worker usually opens 2 connections to gearmand, so you could try to graph the open files next to the number of the worker processes (which are dynamic).

**Comment by p-alik** [comment]
Thanks for reply @sni. I guess our reporters use newer gearmand but unfortunately they didn't reply to my question in this regard. So I close the issue and I'll get in touch if I'll get any new information.

**Comment by p-alik** [comment]
TYMBI https://github.com/gearman/gearmand/issues/102
