### ISSUE TITLE
Mod_gearman 3.0.1 doesn't parse line returns correctly

### ISSUE THREAD

**Issue by McRiverside** [sni/mod_gearman#112]
Hi,

We have a Nagios XI 5.4.2 alonside with gearmand 0.33 runnning. Every mod_gearman_worker runs the 3.0.1 version.

Mod_gearman doesn't parse multi lines returns in the long_ooutput field as Nagios would normally do, it puts everything into the output field.

Result with mod_gearman:
output: ABC\nDEF\nGHI\n
long_output: _null_
Expected result:
output: ABC
Long_output:DEF\nGHI\n

Can anyone tell me where to change it in the NEB to parse it correctly and make use of the long_output field?

Thank you,
Alexandre

**Comment by barry-luijten** [comment]
mod-gearman 3.0.0 and 3.0.3 also seem to have this issue. Newlines are not parsed and are appended  as "\n" to the perfdata and plugin_output string...
Example:
```
Status Information:	OK - load average: 2.17, 2.02, 1.53
Performance Data:	load1=2.170;25.000;30.000;0; load5=2.020;15.000;20.000;0; load15=1.530;10.000;15.000;0; \n
```

**Comment by sni** [comment]
I don't have access to any nagios xi, maybe @hedenface want to have a look

**Comment by hedenface** [comment]
I'll take a look.

**Comment by hedenface** [comment]
Fixed in #118 PR.

**Comment by barry-luijten** [comment]
Thanks Bryan! I hope it will be merged swiftly :)

**Comment by wleese** [comment]
Currently trying to track down an issue with nagios crashing - could this issue have such an impact? (https://github.com/NagiosEnterprises/nagioscore/issues/391)

**Comment by sni** [comment]
Merged, thanks.
