### ISSUE TITLE
Unable to add more workers in check_results queue

### ISSUE THREAD

**Issue by ranjithkodumbu** [sni/mod_gearman#113]
Hi All,

I am using gearman with Nagios xi. I have tried adding "result_workers=2" parameter in "/etc/mod_gearman/module.conf" file and restarted nagios and gearmand service. when I ran gearman_top command, I could see only 1 worker for check_result queue. Please help me on this issue.

broker_module=/usr/lib64/mod_gearman/mod_gearman_nagios4.o config=/etc/mod_gearman/module.conf

Thanks,
Ranjith Kumar R

**Comment by sni** [comment]
`result_workers` is deprecated and always set to 1. The nagios core processes results serially, so more result_worker wouldn't increase the performance.

**Comment by ranjithkodumbu** [comment]
Hi Sni,

Thanks a lot for your response, please refer the below screenshot where in you can find check_results is "219681". We are using 2,00,000 monitoring services with 10 worker servers, workers are processing as expected, however check_results queue job waiting is high. Is there anyway to make check_results to work fast, I understand from your comment that nagios core process results serially, but still I am awaiting for your advice to make it work.

Thanks a lot for your support.

![check_result](https://cloud.githubusercontent.com/assets/26919410/24745468/7964759e-1ad3-11e7-83f0-251ad4ef65fa.jpg)

**Comment by sni** [comment]
Please refer to the nagios xi support on how to make nagios faster. I am unable to support commercial products.

**Comment by ranjithkodumbu** [comment]
Hi sni,

Thanks a lot for the response. so you meant to say, check_results queue is building because of nagios is not processing?
currently server load is less than 1% . I suspect, by increasing check_result worker might bring down queue build. Is there any way I can try that?

Thanks

**Comment by sni** [comment]
Well, there are older releases which still have this option available. But i'd say there is a different issue somewhere. There must be a reason why these results pile up while the box is idling. There are only 3 blocking events in the core which are eventhandler, notifications and on-demand-hostchecks. Mod-Gearman fixes 2 of them, but notifications are still serial and blocking. Might be worth to look into this.
Some future Mod-Gearman release will btw have notifications support to address that as well.
