### ISSUE TITLE
orphan_return isn't documented or included in default config file

### ISSUE THREAD

**Issue by druchoo** [sni/mod_gearman#114]
`orphan_return` is only in changelog for 1.4.6.

> 1.4.6 Tue Jun  4 17:03:57 CEST 2013
>           ...
>           - added new option 'orphan_return' to set return code of orphaned checks

Other than that reference, it's only found in code:
https://github.com/sni/mod_gearman/search?utf8=%E2%9C%93&q=orphan_return&type=

**Comment by sni** [comment]
Thanks for the pointer. Could you add a small sentence here: https://github.com/sni/mod_gearman/blob/master/README.asciidoc and in the example config files?

**Comment by druchoo** [comment]
How's this #115?

**Comment by sni** [comment]
great, thanks.
