### ISSUE TITLE
undefined symbol process_macros_r in nagios3 module 

### ISSUE THREAD

**Issue by CharlesJUDITH** [sni/mod_gearman#117]
Hi,

We upgraded the mod_gearman from 3.0.1 to 3.0.3, and when Nagios is restarting there is the following error in the logs:

`[1498553573] Error: Could not load module '/usr/lib64/mod_gearman/mod_gearman.o' -> /tmp/nebmodr6LkHU: undefined symbol: process_macros_r`

Nagios version: 3.2.3-6
Gearmand: 0.33
gearmand-server: 0.33
mod_gearman: 3.0.3

It's working with the 3.0.1.

**Comment by sni** [comment]
Seems like that has been introduced in later nagios 3 releases. I've only checked 3.5.1. So you can either upgrade nagios or downgrade mod-gearman.

**Comment by CharlesJUDITH** [comment]
Thanks for your quick feedback ;-)

We'll figure this out.
