### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by jframeau** [sni/mod_gearman#126]
Hi sven,

I think there's a memory leak in mod_gearman (neb_module/result_thread.c, line 229) as neamon doesn't release that source field.

#ifdef USENAEMON
            chk_result->source = gm_strdup( value );
#endif

So my proposition in naemon (head):

--- a/src/naemon/checks.c
+++ b/src/naemon/checks.c
@@ -524,6 +524,7 @@ int free_check_result(check_result *info)
        nm_free(info->host_name);
        nm_free(info->service_description);
        nm_free(info->output);
+       nm_free(info->source);
 
        return OK;
 }

This leak has been found with valgrind.

Do you agree with that ?

jfr

**Comment by sni** [comment]
Sounds good
