### ISSUE TITLE
Guide needed

### ISSUE THREAD

**Issue by AsenZahariev** [sni/mod_gearman#131]
Hello folks,
I was trying to install mod_gearman on centos 7 with latest(stable) version of Nagios core 4 and mod_gearman. Unfortunately i'm hitting the wall too many times. Are there any specific instruction for centos7? 

Thank you!
Asen Z

**Comment by sni** [comment]
Please have a look at https://mod-gearman.org/support.html on how to get support. This is only a issue tracker.
