### ISSUE TITLE
Nagios 4.4.0+ incompatibility

### ISSUE THREAD

**Issue by hedenface** [sni/mod_gearman#136]
@sni do you want me to try and get Nagios Core 4.4.0+ working with mod_gearman? I've identified the issues and am working on it internally - I wouldn't mind submitting this as a PR when complete.

**Comment by sni** [comment]
yes please, just send a PR.

**Comment by sni** [comment]
is there a time plan for this, i'd like to cut a release in the next days and it would probably nice if this is included.

**Comment by nicomatsu** [comment]
@hedenface Do you have an estimated due-delivery date? or can you point me in the right direction to do this modifications myself? This issue is stalling a project

**Comment by fran-pastor** [comment]
Hi all, any news? just like @nicomatsu we have an update of NagiosXI stopped until mod_gearman is compatible with nagios 4.4

**Comment by hedenface** [comment]
Apologies for not responding earlier - I was on holiday/vacation for a while, and am only now getting back into the swing of things. My plans currently are to get a Core 4.4.2 release out followed by a Plugins release. I can try and squeeze a fix in for ModGearman, but I can't commit to a time frame.

@nicomatsu - If your Nagios XI is stalled, please revert the Core version to 4.2.4, as this will fix that problem. The upgrade script for XI checks to see if ModGearman is installed and doesn't update Core if it's found, but if you did a fresh install and then installed MG you will have the issue. But again, simply reverting Core to version 4.2.4 - or using a version of XI before 5.5.0 will also fix the issue.

**Comment by jgbuenaventura** [comment]
hi i can see there there is already a core version 4.4.2 release, is the fix for mod_gearman included on this? thanks!

**Comment by hedenface** [comment]
@jgbuenaventura No it isn't. The fix for mod_gearman won't be in a Core release - it'll be in a mod_gearman release as some of the referenced functions have changed.

**Comment by delboy1966** [comment]
Hi everyone
Is there any update on timeline for a new release of mod_gearman that is compatible with Nagios 4.4.2?

Thanks

**Comment by sni** [comment]
A new release of mod-gearman wouldn't help. I need a PR with the required changes for nagios before that.

**Comment by delboy1966** [comment]
So is it possible to now download the updated version of mod_gearman that works with 4.3.4?

**Comment by sni** [comment]
it is: https://mod-gearman.org/download.html
