### ISSUE TITLE
nagios 4 and gearman proxy, many TIME_WAIT

### ISSUE THREAD

**Issue by adjosan** [sni/mod_gearman#138]
hello

i see a lot of connection timeout from command "netstat -an | grep 4730"
the gearman proxy send  a SYN_SENT to the gearman server every seconds.
do you have already seen this before ?

i'm using on centos 7 : 
nagios 4.3.4
gearmand-0.33-6.x86_64
mod_gearman-3.0.5-1.el7.centos.x86_64
gearmand-server-0.33-6.x86_64
gearmand-devel-0.33-6.x86_64

**Comment by sni** [comment]
no, haven't seen this anywhere. might be a firewall issue?
