### ISSUE TITLE
send_gearman from mod-gearman-tools requires libgearman6, but stable repo installs libgearman7 as a dependency

### ISSUE THREAD

**Issue by firebus** [sni/mod_gearman#141]
Hello,

I installed mod-gearman-tools from the ubuntu 16.04 repo following these instructions: https://labs.consol.de/repo/stable/#_ubuntu_xenial_16_04

When I ran `apt install mod-gearman-tools`

```
The following additional packages will be installed:
  libgearman7
```

But when I run send_gearman:

```
/usr/lib/nagios/plugins/send_gearman: error while loading shared libraries: libgearman.so.6: cannot open shared object file: No such file or directory
```

I can work around with

```
# /usr/lib/x86_64-linux-gnu# ln -s libgearman.so.7.0.1 libgearman.so.6
```

Is there a repo I can install the libgearman6 package from? Or is there a mod-gearman-tools package that contains a send_gearman that's linked to libgearman7?

Thank you!

**Comment by sni** [comment]
If you only need a portable send_gearman, try that one here: https://github.com/ConSol/mod-gearman-worker-go

**Comment by firebus** [comment]
Thank you for the workaround! But this is still a bug in the stable repo that should be fixed at some point.

**Comment by sni** [comment]
actually, its not the labs repository which is broken here, its the ubuntu repository itself which contains packages which the same name but i assume ubuntu repositories have a higher priority. Maybe you can do something with apt pinning.
