### ISSUE TITLE
Jobs waiting in custom queue

### ISSUE THREAD

**Issue by riskersen** [sni/mod_gearman#144]
Hi,

I have to execute a check on a specific worker, so I added custom variable _WORKER to the specific host object in nagios 3.5.1:

`        _WORKER                         hostgroup_workerqueue_wwtoamon0004`

Configuration of the worker:
hostgroups=workerqueue_wwtoamon0004

Nagios output:

`(service check orphaned, is the mod-gearman worker on queue 'hostgroup_workerqueue_wwtoamon0004' running?)`

Output of gearman_top:

 Queue Name                         | Worker Available | Jobs Waiting | Jobs Running
-------------------------------------------------------------------------------------
 hostgroup_workerqueue_wwtoamon0004 |             100  |          12  |           0

As you can see, there are 100 workers available, but the specific host is not fetching the jobs from the queue. I have enabled debug logging on this worker, but there are no entries related to the "pinned" host.

All components have been already restarted.
Worker and gearman server. Gearman related components are being installed from stable consol labs repo:
mod_gearman-3.0.8-1.el7.x86_64
libgearman-devel-1.1.12-18.el7.x86_64
gearmand-0.33-7.x86_64
libgearman-1.1.12-18.el7.x86_64
gearmand-server-0.33-7.x86_64

Could you please provide me a hint? The documentation seems to be clear to me, but perhaps I'm missing a vital point.

Regards
Oliver

**Comment by sni** [comment]
might be related with #145. The jobs get picked up, but will be immediatly added again.

**Comment by riskersen** [comment]
So, the recommendation is to apply the patch mentioned in #145 or will there be an updated package available on consol labs repo?
