### ISSUE TITLE
Is it possible to connect single worker to multiple German server

### ISSUE THREAD

**Issue by ranjithkodumbu** [sni/mod_gearman#148]
Hi Team,

As far as I know, there is no option to use shared worker for multiple German server. For e. g.  In Nagios if I need to connect Notification queue of multiple German servers using single worker will not work as we have only one option in woker.conf file to connect single German server. Please let me know how to achieve this scenario.

**Comment by sni** [comment]
you can specify multiple servers in your worker.cfg. However, this is not recommended. It is simpler and easier to keep separate instances separated. You don't save any resources and the resulting setup is just more complex.
Btw, it's called "gearman" :-)

**Comment by ranjithkodumbu** [comment]
Hi Sni, 
Thanks a lot for the response.
I do agree with you, but managing multiple notification worker is difficult than managing one worker with more resources. E.g. if we need to have multiple worker nodes, need to also manage OS, patching, license etc, that was the reason I asked this question.

**Comment by ranjithkodumbu** [comment]
That was typo :) it is gearman only.

**Comment by sni** [comment]
You can have as many workers on a machine as you like. Just use a different gearman server with a different port

**Comment by ranjithkodumbu** [comment]
Got it, need to run multiple worker process on a single server with unique worker.conf, where each worker.conf should contain unique gearman IP addresses with unique port. Thanks a lot.
