### ISSUE TITLE
Perfdata Truncated via mod_gearman

### ISSUE THREAD

**Issue by infraweavers** [sni/mod_gearman#154]
Good morning,

We have several OMD checks that return huge amounts of perfdata (~ 80kB) we've noticed that these are completely fine into thruk and naemon in general, however our pnp_gearman_worker seems to receive a truncated set of perfdata. 

We've traced this back to here: https://github.com/sni/mod_gearman/blob/6305296842a7fbfbc1aa26602a29322216d492b8/neb_module/mod_gearman.c#L1566

It looks like there's a 64KiB limit on the message size that's enqueued onto the `perfdata` queue. 
Is there any particular reason that this is smaller than `GM_MAX_OUTPUT` (https://github.com/sni/mod_gearman/blob/e56e94be6d677aed55aa776e977a04ffee122cf0/include/common.h#L63)?

Would you accept a PR changing `GM_BUFFERSIZE` up to `10485760` ?

**Comment by sni** [comment]
There is no reason for this, it was a arbitrary limit which i thought it would be enough.
