### ISSUE TITLE
Installation fails on Ubuntu / Debian

### ISSUE THREAD

**Issue by Madic-** [sni/mod_gearman#156]
Installing mod-gearman-module from console stable repository on a debian (based) distribution leads to the following error:
```
Setting up mod-gearman-module (3.3.3) ...
gzip: /etc/mod-gearman/module.conf.gz: unexpected end of file
dpkg: error processing package mod-gearman-module (--configure):
 installed mod-gearman-module package post-installation script subprocess returned error exit status 1
 ```
The file /etc/mod-gearman/module.conf.gz has 0 bytes.
It also requires the user and group naemon to be present.

The package from https://mod-gearman.org/download/v3.3.3/ubuntu20.04/amd64/ has the same problems.

How can I, apart from OMD, install mod-gearman-module on a debian (based) dsitribution?

## Edit
So postinst tries to **cp -p /usr/share/doc/mod-gearman-module/examples/module.conf.gz /etc/mod-gearman/module.conf.gz**
But /usr/share/doc/mod-gearman-module/examples/module.conf.gz is not present, although the path in the data.tar.xz package is correct

**Comment by sni** [comment]
But i see, the naemon user is only created in the worker preinst. Did you install the module only? Did you install naemon-core before?

**Comment by sni** [comment]
I added naemon-core to the module dependencies: 73bbe45984430db703b08db80d1f68dbd8787746

**Comment by Madic-** [comment]
I only installed the module, not the core. Thank you for your help
