### ISSUE TITLE
Worker in Raspberry Pi 4

### ISSUE THREAD

**Issue by ljacobo** [sni/mod_gearman#161]
Hi, 

I am trying to install from source the mod_gearman-4.0.0 but when is configuring, gives me the error:

```
configure: error: Package requirements (naemon >= 1.2) were not met:

No package 'naemon' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables naemon_CFLAGS
and naemon_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

There is a way to only install the WORKER?  I have already running the gearman server with Naemon.

Thanks.

**Comment by sni** [comment]
It is possible to install the worker only. However, the configure is not smart enough to only build the worker. However, this c worker is deprecated anyway. Better use the new go worker: https://github.com/ConSol/mod-gearman-worker-go/
It uses less ressources and can be build standalone without naemon header files.
