### ISSUE TITLE
[RHEL 9] - Deployment

### ISSUE THREAD

**Issue by thomasjcf29** [sni/mod_gearman#163]
Hi,

Would it please be possible to get this built for RHEL 9?

We have some servers in production we would like to install this on, but are currently not able too :)))

Many Thanks,
Tom.

**Comment by sni** [comment]
so far, there is no rhel9 available on https://build.opensuse.org/projects/home:naemon/ and i have no idea about their plans when they add it.
The newest rpm based os is fedora 36, but no idea how compatible they are. You could always build the RPMs yourself.

**Comment by thomasjcf29** [comment]
Hey @sni, I think they've released an RL9 version, if possible please could we get an RL9 version of mod-gearman? :)

**Comment by sni** [comment]
they have alma 9 now, should work well with rhel 9 too. I enabled the repositories and the build looks fine.

**Comment by thomasjcf29** [comment]
Thanks very much, I appreciate the quick turnaround :)
