### ISSUE TITLE
mod-gearman-worker 4.0.3 on labs.consol.de not compatible with naemon 1.4.0

### ISSUE THREAD

**Issue by r-lindner** [sni/mod_gearman#165]
Hello,

Naemon 1.4.0 was released some days ago and mod-gearman-worker hosted in the debian repository at labs.consol.de is not compatible with it (segmentation fault). According to the Naemon Changelog it needs to be recompiled.

Thanks for this great piece of software, much better than Naemon on its own :)

**Comment by sni** [comment]
Hi,

with the recent naemon update, all NEB modules need to be rebuild. I did that with Mod-Gearman 4.0.4 which is going to be released tomorrow.

Cheers,
  Sven

**Comment by r-lindner** [comment]
Thanks, now it is working.
