### ISSUE TITLE
Ubuntu 22 support?

### ISSUE THREAD

**Issue by rduffner** [sni/mod_gearman#168]
Hi,

do you know if Ubuntu 22 builds can be added?

Additionally, we still use icinga1...

**Comment by sni** [comment]
There are ubuntu 22.04 builds here:
https://build.opensuse.org/project/show/home:naemon
But i don't think they still work with icinga1. The mod-gearman neb 4.x supports Naemon only.

**Comment by rduffner** [comment]
Yes, I saw that V4 is not compatible with icinga1, which sadly we still use.

**Comment by sni** [comment]
Depending on the reasons, you could give naemon (https://www.naemon.io) a try. It has the same config syntax.

**Comment by rduffner** [comment]
We plan to switch to icinga2 next year.
