### ISSUE TITLE
Nagios >= 4.4.7 and libnagios

### ISSUE THREAD

**Issue by jbeaujour** [sni/mod_gearman#169]
Hello
There is this update in Nagios 4.4.7 :
4.4.7 - 2022-04-14
------------------
FIXES
* Added SSL support for version update check (Sebastian Wolf)
* **_Note: NEB modules using the priority/scheduling queues in libnagios may need to update headers due to symbol conflicts with OpenSSL._**

Is mod_gearman affected by this evolution ?
And corrected if necessary ?
thank's

**Comment by jbeaujour** [comment]
Do we still use NAGIOS + ( LIVESTATUS + MOD_GEARMAN_NEB) + THRUK ?

**Comment by sni** [comment]
No, Mod-Gearman dropped Nagios/Icinga1 support starting with the 4.x release.
