### ISSUE TITLE
mod_gearman_naemon.o 5.1.2 is using an old or unspecified version of the event broker API

### ISSUE THREAD

**Issue by r-lindner** [sni/mod_gearman#170]
Hi :)

I tried to update mod-gearman-module to 5.1.2 but got this error:

> Module '/usr/lib/x86_64-linux-gnu/mod_gearman/mod_gearman_naemon.o' is using an old or unspecified version of the event broker API.  Module will be unloaded.

The previous version in the consol debian repository (5.1.0) can be loaded.

> ii naemon-core 1.4.1 amd64
> ii mod-gearman-module 5.1.2 amd64

Am I doing something wrong?

**Comment by sni** [comment]
are you using naemon and mod-gearman from the same repository?

**Comment by r-lindner** [comment]
yes, both are from
> deb-amd64 https://labs.consol.de/repo/stable/debian bullseye main

```bash
# sha256sum /usr/bin/naemon /usr/lib/x86_64-linux-gnu/mod_gearman/mod_gearman_naemon.o
a9b51aec63035442c7b10aa2d82f95984592c7e9de8a73f14fa2140bcd513b70  /usr/bin/naemon
676c5d4599b56e28319829877f5ac335cd9cae06a3e45795a4376896f97a68fd  /usr/lib/x86_64-linux-gnu/mod_gearman/mod_gearman_naemon.o
```

**Comment by r-lindner** [comment]
I compiled mod-gearman-module from source and it is working this way. The current naemon-dev package ships nebmodules.h with CURRENT_NEB_API_VERSION=5, whereas you compiled mod-gearman-module with CURRENT_NEB_API_VERSION=6. naemon-dev v1.4.1 is from February 2023 and the change in github is from 3 weeks ago.

**Comment by sni** [comment]
i see, i think i know the reason. The labs repository merges stable/testing repo to solve dependencies. Also old releases are not rebuild automatically if dependencies change.
This is one of the reasons why i want to move the repository to the OBS build server. OBS
handles such dependencies much better.
The repository is here:
https://build.opensuse.org/project/show/home:naemon

**Comment by r-lindner** [comment]
the dependency I need (naemon-dev) is missing in this repository ;)

**Comment by sni** [comment]
it should be there, ex.:
https://build.opensuse.org/package/binaries/home:naemon/naemon-core/Debian_11

**Comment by r-lindner** [comment]
oh you are right but I cannot find a way to use the repository because there is no **dists** folder and the directory structure does not conform to what Debian/Apt expects.

**Comment by sni** [comment]
Here is how you can use it as apt repository: https://www.naemon.io/download/#debian

```
curl -s -o /etc/apt/trusted.gpg.d/naemon.asc https://build.opensuse.org/projects/home:naemon/signing_keys/download?kind=gpg
echo "deb [signed-by=/etc/apt/trusted.gpg.d/naemon.asc] http://download.opensuse.org/repositories/home:/naemon/Debian_$(lsb_release -rs)/ ./" >> /etc/apt/sources.list.d/naemon-stable.list
apt-get update
```

**Comment by r-lindner** [comment]
oh, I could have looked at the documentation... With the opensuse repository it is now working. Thanks.

**Comment by Akulatraxas** [comment]
I have the same issue under rocky8. I had to go back to 5.1.0. Everything is installed from the labs_consol_stable. 
I am not sure if i read this issue correctly. Will it be fixed or do i have to change something?

```
yum list installed | egrep 'naemon|mod_gearman'
libnaemon.x86_64                            1.4.1-0                                    @labs_consol_stable
mod_gearman.x86_64                          5.1.0-1.el8                                @labs_consol_stable
naemon.noarch                               1.4.1-0                                    @labs_consol_stable
```

**Comment by sni** [comment]
it will be fixed in the next release. But it is fixed in the packages from OBS which i advise to use anyway.
