### ISSUE TITLE
how many mod_gearman _worker max ?

### ISSUE THREAD

**Issue by jbeaujour** [sni/mod_gearman#174]
Hello
In the future, our network architecture will require us to have more than 250 mod_gearman_worker (1 per network) and 1 mod_gearman_neb with NAGIOS/NAEMON.
Today we have 20 mod_gearman_worker
There will be as many hosts/services as today (20000/150000)
Is there a limit for the number of mod_gearman_worker connected to mod_gearman_neb?
Will there be a strong increase in load/memory/etc. on CORE NAGIOS/NAEMON?
THANKS

**Comment by sni** [comment]
The limit is the number of open files on the gearmand usually. That beeing said, i know naemon setups with 1.5mio services (using 1 naemon + 10 worker machines).
Spreading the services on 250 or 10 worker should not affect the load.

**Comment by jbeaujour** [comment]
Thank you once again for your speed and availability in answering our questions.
In this specific case, this will allow us to develop our monitoring platform without fear.
Have a nice week end
