### ISSUE TITLE
log_global_notifications not yet released in naemon-core

### ISSUE THREAD

**Issue by pvdputte** [sni/mod_gearman#179]
The latest release of mod-gearman-module references `log_global_notifications`:
https://github.com/sni/mod_gearman/commit/5e868d5525a5482ad5293cabab08a933fa46bc2b

But the latest release of naemon-core does not have that yet. Cfr. https://github.com/naemon/naemon-core/commit/9b04b4554e3a3e21c705b08afc647a8a0a0f91ec

As a result, today my Debian 12 test-hosts were rebuilt with naemon-core 1.4.2 and mod-gearman-module 5.6.1 but the module cannot be loaded anymore:
```
[2024-11-14 22:47:08] [1731620828] Error: Could not load module '/usr/lib/x86_64-linux-gnu/mod_gearman/mod_gearman_naemon.o' -> /usr/lib/x86_64-linux-gnu/mod_gearman/mod_gearman_naemon.o: undefined symbol: log_global_notifications
[2024-11-14 22:47:08] [1731620828] Error: Failed to load module '/usr/lib/x86_64-linux-gnu/mod_gearman/mod_gearman_naemon.o'.
[2024-11-14 22:47:08] [1731620828] Error: Module loading failed. Aborting.
```

I'm afraid that doing an `apt upgrade` right now would break systems.

**Comment by pvdputte** [comment]
Thanks for your response.

Only the last version is available on the package server it seems http://download.opensuse.org/repositories/home:/naemon/Debian_12/

I'll see if I can work around it until then with an older .deb from `/var/cache/apt/archives`.

**Comment by sni** [comment]
you could also try to use the nightly builds from here: https://download.opensuse.org/repositories/home:/naemon:/daily/Debian_12/

**Comment by sni** [comment]
should be fine now with the latest naemon v1.4.3 release.

**Comment by pvdputte** [comment]
Now I'm having other trouble with the regular repo again, namely
```
E: Failed to fetch http://ftp.gwdg.de/pub/opensuse/repositories/home%3A/naemon/Debian_12/amd64/mod-gearman-module_5.1.6-1_amd64.deb  File has unexpected size (296808 != 296872). Mirror sync in progress? [IP: 134.76.12.6 80]
   Hashes of expected file:
    - SHA256:0ee5a6291c3f19b19962f22739df920709a71ec3fd5122edf646e41c1648e3b3
    - SHA1:9f59de94f1a4dbfe019be3a049cd2735d5d17d36 [weak]
    - MD5Sum:425d3ea6c4ef5bbfcdbf752d8f38afbb [weak]
    - Filesize:296872 [weak]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

# wget http://ftp.gwdg.de/pub/opensuse/repositories/home%3A/naemon/Debian_12/amd64/mod-gearman-module_5.1.6-1_amd64.deb
--2024-11-19 11:22:50--  http://ftp.gwdg.de/pub/opensuse/repositories/home%3A/naemon/Debian_12/amd64/mod-gearman-module_5.1.6-1_amd64.deb
Resolving ftp.gwdg.de (ftp.gwdg.de)... 134.76.12.6, 2a06:93c7:f0::f79
Connecting to ftp.gwdg.de (ftp.gwdg.de)|134.76.12.6|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 296808 (290K) [application/octet-stream]
Saving to: ‘mod-gearman-module_5.1.6-1_amd64.deb’

mod-gearman-module_5.1.6-1_amd64.deb              100%[=========================>] 289.85K  --.-KB/s    in 0.08s   

2024-11-19 11:22:50 (3.75 MB/s) - ‘mod-gearman-module_5.1.6-1_amd64.deb’ saved [296808/296808]

$ md5sum mod-gearman-module_5.1.6-1_amd64.deb
edad926975c6cf7c0581f0771a83d029  mod-gearman-module_5.1.6-1_amd64.deb
```

That is not matching `425d3ea6c4ef5bbfcdbf752d8f38afbb` indeed :thinking:

**Comment by pvdputte** [comment]
BTW, using
```deb [signed-by=/etc/apt/trusted.gpg.d/naemon.asc] http://download.opensuse.org/repositories/home:/naemon/Debian_12/ ./```

**Comment by pvdputte** [comment]
Looks like a mirror problem :disappointed: 

If I explicitly point ftp.gwdg.de to 195.135.223.226 (i.e. 195.135.223.226), I get the correct .deb.

```
$ md5sum mod-gearman-module_5.1.6-1_amd64.deb*
edad926975c6cf7c0581f0771a83d029  mod-gearman-module_5.1.6-1_amd64.deb
425d3ea6c4ef5bbfcdbf752d8f38afbb  mod-gearman-module_5.1.6-1_amd64.deb.1
```

**Comment by sni** [comment]
that's not really under our control, especially the mirrors.

Besides that, did it help?

**Comment by pvdputte** [comment]
Yes, all packages are now in working order again :+1:  Just wanted to let you know as I was pulling my hair out because I thought apt-cacher-ng was at fault.

I'll resort to setting that override in `/etc/hosts` for now then, not really an issue for me but it might annoy others.

Meanwhile I'm finding out why the histou scripted dashboard won't work anymore with grafana 11.3 :rofl: It's one of those days.

But this issue here is fixed, that's for sure. Thanks.

**Comment by snarf6** [comment]
Hi,

Seems there's still some issues with files . MD5Sum expected from the Package file in repo is `425d3ea6c4ef5bbfcdbf752d8f38afbb`

but : 

```
edad926975c6cf7c0581f0771a83d029  mod-gearman-module_5.1.6-1_amd64.deb <-- my mirror
edad926975c6cf7c0581f0771a83d029  mod-gearman-module_5.1.6-1_amd64.deb.1 <--  ftp.gwdg.de mirror
edad926975c6cf7c0581f0771a83d029  mod-gearman-module_5.1.6-1_amd64.deb.2 <-- opensuse repo 
```

Looks like there're something with the hash, and the previous version of the module (the one with the  log_global_notifications issue had a correct hash regarding to the Package file)

Thx

**Comment by pvdputte** [comment]
The only "fix" I have is putting `195.135.223.226 ftp.gwdg.de` in the `/etc/hosts` file + `apt update`.

In my experience the opensuse repo redirected to that gwdg.de mirror.

**Comment by snarf6** [comment]
so, there something REALLY fun .... 

```
edad926975c6cf7c0581f0771a83d029  mod-gearman-module_5.1.6-1_amd64.deb  <-- my mirror 
edad926975c6cf7c0581f0771a83d029  mod-gearman-module_5.1.6-1_amd64.deb.1 <-- ftp.gwdg.de mirror
edad926975c6cf7c0581f0771a83d029  mod-gearman-module_5.1.6-1_amd64.deb.2 <-- opensuse repo 
7829078494f4e9c933a73a6373039636  mod-gearman-module_5.1.6-1_amd64.deb.3 <- 195.135.223.226 direct
425d3ea6c4ef5bbfcdbf752d8f38afbb  mod-gearman-module_5.1.6-1_amd64.deb.4 <- 195.135.223.226 as ftp.gwdg.de resolution
```
So we can assume that's something broken on opensuse repos ?

**Comment by snarf6** [comment]
i think this is more an issue with some cache on the opensuse side

direct download from download.opensuse.org seems better now 

```
[snarf:~] $ curl -s http://download.opensuse.org/pub/opensuse/repositories/home:/naemon/Debian_11/amd64/mod-gearman-module_5.1.6-1_amd64.deb | md5sum
7829078494f4e9c933a73a6373039636  -
[snarf:~] $ curl -s http://download.opensuse.org/pub/opensuse/repositories/home:/naemon/Debian_12/amd64/mod-gearman-module_5.1.6-1_amd64.deb | md5sum
425d3ea6c4ef5bbfcdbf752d8f38afbb  -
```
