### ISSUE TITLE
results never came back

### ISSUE THREAD

**Issue by twscl** [sni/mod_gearman#71]
Sorry ！My mistake!
i got the Mod_Gearman for nagios3 version(github).
implement it.

I got an error message.
==== icinga log =====
[Mon Jan 19 18:30:52 2015] Warning: The check of service 'Oracle Tablespace' on host 'dbca.personal.com' looks like it was orphaned (results never came back; last_check=Mon Jan 19 15:15:31 2015; next_check=Mon Jan 19 15:15:31 2015).  I'm scheduling an immediate check of the service...
================

i guess in common/check_utils.c :308
 pipe stdout -- In Linux, the size of the buffer is 65536 bytes.

Can you help me?

**Comment by sni** [comment]
Could you try the latest release?
