### ISSUE TITLE
Error if one of several gearmand servers is down

### ISSUE THREAD

**Issue by adrianlzt** [sni/mod_gearman#75]
Environment:
RedHat 6.5
gearmand-server-0.33-2.x86_64
gearmand-0.33-2.x86_64
mod_gearman-1.5.2-1.el6.x86_64

mod_gearman_neb.conf
```
server=localhost:4730
server=172.16.1.31:4730
```

If server 172.16.1.31 is down, mod_gearman_neb writes this to log file:
```
[2015-02-27 10:43:51][2769][ERROR] sending job to gearmand failed: connect_poll(No route to host) getsockopt() failed -> libgearman/connection.cc:104
[2015-02-27 10:43:51][2769][ERROR] worker error: connect_poll(No route to host) getsockopt() failed -> libgearman/connection.cc:104
[2015-02-27 10:43:54][2769][ERROR] worker error: connect_poll(No route to host) getsockopt() failed -> libgearman/connection.cc:104
```

But, if 172.16.1.31 is up but gearmand-server down, all works properly.

I have compiled mod_gearman 1.5.2 to use gearmand-1.0.6 and works correctly.
Packages:
https://drive.google.com/open?id=0B84NO1oyhUXva3A5NHdnMThReGM&authuser=0
https://drive.google.com/open?id=0B84NO1oyhUXvWHNPMzhCcTE4UDQ&authuser=0
https://drive.google.com/open?id=0B84NO1oyhUXvMlNCN0IzQW9rOEU&authuser=0
https://drive.google.com/open?id=0B84NO1oyhUXvbUZtd1RnaDBXN0U&authuser=0

**Comment by adrianlzt** [comment]
The cure is worse than the disease.
With gearmand-1.0.6, if no gearmand is available, mod_gearman_neb start to create sockets until file descriptors exhaustion.
Also, with running gearmand, if Icinga tries to execute an active check it gets stuck.

Going back to gearmand 0.33 using pacemaker to give HA.

**Comment by adrianlzt** [comment]
terminar el feature/all_in_one
tdaf-api-cyclops/neore/deploy/

**Comment by sni** [comment]
i haven't made good results with any gearman version > 0.33.
Here is a list of working versions: http://labs.consol.de/nagios/mod-gearman/#_supported_dependencies

**Comment by sni** [comment]
Could you give the latest release a try. I fixen an issue with segfaulting on connection errors.
