### ISSUE TITLE
Help Wanted - Distributing Event Handler Checks throughout workers

### ISSUE THREAD

**Issue by bernardoVale** [sni/mod_gearman#80]
We are using mod_gearman to distribute checks on hosts/services behind firewalls. Now we want also use event handler on those hosts/services.

This host/services communicate only with one worker and the worker  with Nagios Server/Mod Gearman.

![distribute](https://cloud.githubusercontent.com/assets/1888123/10367825/f26f7b48-6da8-11e5-928a-d2e8f10e67ce.png)

I've tried to configure this setting eventhandler=yes but the event handlers are always passed to the local worker inside Nagios Server/Mod Gearman.

**Comment by sni** [comment]
You have to set "route_eventhandler_like_checks=yes", then eventhandler will end up on the same worker as their host/service checks would be.

Also please use the mailing list for general questions and support so other users can answer too. This tracker is mostly used for bugs and issues.

**Comment by bernardoVale** [comment]
Thanks Sven, I've opened a thread on mailing list https://groups.google.com/forum/#!topic/mod_gearman/XBJsUZOB49c
