### ISSUE TITLE
Version 3 released ?

### ISSUE THREAD

**Issue by box293** [sni/mod_gearman#87]
I see this in the readme on the main github page:

Latest stable release version 3.0.0, released Februar 25 2016

It points to:

http://www.mod-gearman.org/download/v3.0.0/src/mod_gearman-3.0.0.tar.gz

However that link fails. Nothing v3 related is shown here: http://www.mod-gearman.org/download/

**Comment by sni** [comment]
There is no v3.0.0 yet, this is still work in progress. You can subscribe to the mailing list. I will announce the release there when it's ready.
