### ISSUE TITLE
check_gearman CRITICAL - Job failed: _client_do(GEARMAN_TIMEOUT) occured during gearman_client_run_tasks() - libgearman/client.cc:174

### ISSUE THREAD

**Issue by druchoo** [sni/mod_gearman#90]
Receiving check_gearman error every few weeks or so. Restarting gearmand resolves. Issue seems to be just check_gearman as mod_gearman still processes Any idea on cause or fix?

[Old post about issue](https://groups.google.com/forum/#!searchin/mod_gearman/GEARMAN_TIMEOUT/mod_gearman/HCKNth14l7o/mzr7G0FArCsJ)

```
$ cat /etc/redhat-release ; rpm -qa | grep gear
Red Hat Enterprise Linux Server release 6.6 (Santiago)
mod_gearman-1.5.5-1.el6.x86_64
gearmand-0.33-4.x86_64
gearmand-server-0.33-4.x86_64
```

**Comment by sni** [comment]
No idea. Never had such kind of issues. You could increase the gearmand loglevel, maybe it prints some kind of helpful information.

**Comment by druchoo** [comment]
I've had `debug=3` on during issue and nothing noticeable in log. The worker still processes jobs only issue appears to be check_gearman and trying to stop worker requires `kill -9`.
