### ISSUE TITLE
pidfile path in centos7 systemd module

### ISSUE THREAD

**Issue by dmitriykulishenko** [sni/mod_gearman#94]
in centos7 systemd module the worker's pidfile path is hardcoded, and overrides parameter in worker.conf
so, if you change default pid path in worker.conf it still uses the path from systemd script
(/var/mod_gearman2 by default)

**Comment by dmitriykulishenko** [comment]
this issue persists on version3 too
mod_gearman-3.0.0b1-1.el7.centos.x86_64

**Comment by sni** [comment]
I'd say this works as intented. Mod-Gearman read the command line arguments from left to right and the last one overwrites the previous setting. Also i think its a bad idea to change the pid file location when using systemd. Or at least change it in the services file and in the config of mod-gearman.
