### ISSUE TITLE
Crash Naemon

### ISSUE THREAD

**Issue by dmitriykulishenko** [sni/mod_gearman#95]
after upgrade to Naemon 1.04 got this error:
Error: Could not load module '/usr/lib64/mod_gearman2/mod_gearman2.o' -> /usr/lib64/mod_gearman2/mod_gearman2.o: undefined symbol: clear_volatile_macros

mod_gearman2-2.1.5-1.el7.centos.x86_64
naemon-1.0.4-1.el7.centos.x86_64

**Comment by sni** [comment]
You have to use the 3.0 preview version, see https://github.com/naemon/naemon-core/issues/136
