### ISSUE TITLE
Write c to c++

### ISSUE THREAD

**Issue by jben94** [sni/mod_gearman#96]
Hello,

Do you think it would be possible to rewrite this plug-in C ++.
Because I use centengine which is a fork of Nagios but written in C ++ and I have problems on the memory release.

Thank you in advance for your answer.

**Comment by sni** [comment]
Sorry, this won't happen with Mod-Gearman. Afaik centreon has its own solution for distributed monitoring.

**Comment by jben94** [comment]
Bonjour,

Oui vous avez raison pour la partie distributed monitoring mais pas pour le loadbalancing des check.

Merci comme même
