### ISSUE TITLE
V3.0.0b-1.el7  nagios4 startup issue

### ISSUE THREAD

**Issue by jkilborn67** [sni/mod_gearman#97]
Centos 7.2, , nagios 4.0.8-2, mod_gearman v3.0.0b-1.el7
Installed from labs-consol-testing repository

Has this configuration been tested? I can't get nagios to start when setting the broker_module to:
### broker_module=/usr/lib64/mod_gearman/mod_gearman_nagios4.o  config=/etc/mod_gearman/module.conf

systemd: Started Nagios Network Monitoring.
### Could not load module '/usr/lib64/mod_gearman/mod_gearman_nagios4.o' -> /usr/lib64/mod_gearman/mod_gearman_nagios4.o: undefined symbol: check_result_info

Any ideas would be appreciated.

**Comment by sni** [comment]
The nagios 4 part has been contributed by nagios inc. and i did not test it myself since i don't have any nagios 4 installation. Maybe @hedenface can have a look at it.

**Comment by hedenface** [comment]
I can confirm that this behavior exists when installing from the repo. It does NOT when compiling from source (configure with --disable-naemon-neb-module --disable-nagios3-neb-module --with-user=nagios).

**Comment by jkilborn67** [comment]
Thanks for the reply, I will compile from source. Appreciate the help!

**Comment by jkilborn67** [comment]
I compiled from source, and using the configure options from @hedenface , the mod_gearman_nagios4.o worked fine. Nagios is using the broker successfully.

**Comment by sni** [comment]
Can you retry the latest beta 2 from https://mod-gearman.org/download/v3.0.0b2/
(also available in the labs testing repository)

**Comment by jkilborn67** [comment]
I�ll try to test it out tomorrow, and let you know the results.
Thanks

Sent from Windows Mail
