### ISSUE TITLE
Checks constantly resubmitting

### ISSUE THREAD

**Issue by elmobp** [sni/mod_gearman#98]
Ive got a few basic checks setup in naemon 1.0.5 with gearman latest it looks as though the checks keep on resubmitting

2016-08-18 15:47:40  -  localhost:4730  -  v1.0.6

 Queue Name                                         | Worker Available | Jobs Waiting | Jobs Running
-----------------------------------------------------------------------------------------------------
 check_results                                      |               1  |           0  |           0
 host                                               |               0  |           6  |           0
 service                                            |               6  |          10  |           6
 worker_syd03-pmdh-gearman-01 |               2  |           0  |           0
 worker_syd03-pmdh-gearman-02 |               2  |           0  |           0
 worker_syd03-pmdh-gearman-03 |               2  |           0  |           0
 worker_syd03-pmdh-gearman-04 |               2  |           0  |           0
-----------------------------------------------------------------------------------------------------

Jobs running never hits 0 it only has 4/5 checks associated with it.. Any ideas? encryption keys match up on the workers vs the naemon host

**Comment by elmobp** [comment]
Further to that on the worker it self

Aug 18 16:07:08 syd03-pmdh-gearman-01 kernel: [ 6701.907550] mod_gearman2_wo[3133]: segfault at 174e58890 ip 00007fa47540b08c sp 00007ffc6d16bef0 error 4 in libgearman.so.7.0.1[7fa475406000+21000]
Aug 18 16:07:09 syd03-pmdh-gearman-01 kernel: [ 6702.892463] mod_gearman2_wo[3149]: segfault at 174e58890 ip 00007fa47540b08c sp 00007ffc6d16be60 error 4 in libgearman.so.7.0.1[7fa475406000+21000]
Aug 18 16:07:09 syd03-pmdh-gearman-01 kernel: [ 6702.893059] mod_gearman2_wo[3150]: segfault at 174e58890 ip 00007fa47540b08c sp 00007ffc6d16be60 error 4 in libgearman.so.7.0.1[7fa475406000+21000]
Aug 18 16:07:09 syd03-pmdh-gearman-01 kernel: [ 6702.899064] mod_gearman2_wo[3148]: segfault at 174e58890 ip 00007fa47540b08c sp 00007ffc6d16be60 error 4 in libgearman.so.7.0.1[7fa475406000+21000]
Aug 18 16:07:09 syd03-pmdh-gearman-01 kernel: [ 6702.899149] mod_gearman2_wo[3146]: segfault at 174e58890 ip 00007fa47540b08c sp 00007ffc6d16be60 error 4 in libgearman.so.7.0.1[7fa475406000+21000]
Aug 18 16:07:09 syd03-pmdh-gearman-01 kernel: [ 6702.905222] mod_gearman2_wo[3147]: segfault at 174e58890 ip 00007fa47540b08c sp 00007ffc6d16be60 error 4 in libgearman.so.7.0.1[7fa475406000+21000]
Aug 18 16:07:13 syd03-pmdh-gearman-01 kernel: [ 6706.899934] show_signal_msg: 17 callbacks suppressed
Aug 18 16:07:13 syd03-pmdh-gearman-01 kernel: [ 6706.899939] mod_gearman2_wo[3216]: segfault at 174e58890 ip 00007fa47540b08c sp 00007ffc6d16be60 error 4 in libgearman.so.7.0.1[7fa475406000+21000]
Aug 18 16:07:13 syd03-pmdh-gearman-01 kernel: [ 6706.901771] mod_gearman2_wo[3219]: segfault at 174e58890 ip 00007fa47540b08c sp 00007ffc6d16be60 error 4 in libgearman.so.7.0.1[7fa475406000+21000]
Aug 18 16:07:13 syd03-pmdh-gearman-01 kernel: [ 6706.906100] mod_gearman2_wo[3218]: segfault at 174e58890 ip 00007fa47540b08c sp 00007ffc6d16be60 error 4 in libgearman.so.7.0.1[7fa475406000+21000]
Aug 18 16:07:14 syd03-pmdh-gearman-01 kernel: [ 6707.893657] mod_gearman2_wo[3233]: segfault at 174e58890 ip 00007fa47540b08c sp 00007ffc6d16be60 error 4 in libgearman.so.7.0.1[7fa475406000+21000]
Aug 18 16:07:14 syd03-pmdh-gearman-01 kernel: [ 6707.894308] mod_gearman2_wo[3237]: segfault at 174e58890 ip 00007fa47540b08c sp 00007ffc6d16be60 error 4 in libgearman.so.7.0.1[7fa475406000+21000]
Aug 18 16:07:14 syd03-pmdh-gearman-01 kernel: [ 6707.900152] mod_gearman2_wo[3238]: segfault at 174e58890 ip 00007fa47540b08c sp 00007ffc6d16be60 error 4 in libgearman.so.7.0.1[7fa475406000+21000]
Aug 18 16:07:14 syd03-pmdh-gearman-01 kernel: [ 6707.900587] mod_gearman2_wo[3234]: segfault at 174e58890 ip 00007fa47540b08c sp 00007ffc6d16be60 error 4 in libgearman.so.7.0.1[7fa475406000+21000]
Aug 18 16:07:14 syd03-pmdh-gearman-01 kernel: [ 6707.906461] mod_gearman2_wo[3235]: segfault at 174e58890 ip 00007fa47540b08c sp 00007ffc6d16be60 error 4 in libgearman.so.7.0.1[7fa475406000+21000]
Aug 18 16:07:15 syd03-pmdh-gearman-01 kernel: [ 6708.899149] mod_gearman2_wo[3253]: segfault at 174e58890 ip 00007fa47540b08c sp 00007ffc6d16be60 error 4 in libgearman.so.7.0.1[7fa475406000+21000]
Aug 18 16:07:15 syd03-pmdh-gearman-01 kernel: [ 6708.899352] mod_gearman2_wo[3251]: segfault at 174e58890 ip 00007fa47540b08c sp 00007ffc6d16be60 error 4 in libgearman.so.7.0.1[7fa475406000+21000]
Aug 18 16:07:18 syd03-pmdh-gearman-01 kernel: [ 6711.908711] show_signal_msg: 15 callbacks suppressed
Aug 18 16:07:18 syd03-pmdh-gearman-01 kernel: [ 6711.908718] mod_gearman2_wo[3297]: segfault at 174e58890 ip 00007fa47540b08c sp 00007ffc6d16be60 error 4 in libgearman.so.7.0.1[7fa475406000+21000]
Aug 18 16:07:18 syd03-pmdh-gearman-01 kernel: [ 6711.909093] mod_gearman2_wo[3298]: segfault at 174e58890 ip 00007fa47540b08c sp 00007ffc6d16be60 error 4 in libgearman.so.7.0.1[7fa475406000+21000]
Aug 18 16:07:18 syd03-pmdh-gearman-01 kernel: [ 6711.915365] mod_gearman2_wo[3299]: segfault at 174e58890 ip 00007fa47540b08c sp 00007ffc6d16be60 error 4 in libgearman.so.7.0.1[7fa475406000+21000]

**Comment by elmobp** [comment]
Source compile fixed it

**Comment by sni** [comment]
what system is that? Centos 7?

**Comment by sni** [comment]
Can you retry the latest beta 2 from https://mod-gearman.org/download/v3.0.0b2/
(also available in the labs testing repository)

**Comment by elmobp** [comment]
Ubuntu 14.04 ill spin up a few dev servers this is now in production! for now I am managing my own packages
