### ISSUE TITLE
problem with backslashes in commandline (e.g. 'C:\' windows volume check) 

### ISSUE THREAD

**Issue by anfoe1111** [sni/mod_gearman#99]
mod_gearman: 3.0.0.b2-1.el7 installed from labs_consol_testing
naemon: 1.0.5-1.el7 installed from labs_consol_stable
NSClient++ 0.5.0.45 running on a monitored windows-server

Problem:
When a check-command is executed by mod_gearman containing a backslash surrounded by single quotes (e.g. 'C:\'), the backslash will be duplicated in checkresults. Running the same command by a naemon worker dows not show duplicate backslashes.

Example (NSClient++, windows-server):
check_nrpe -H <host-IP-address> -p 5666 -c check_drivesize -a 'drive=C:\' 'perf-config=*(unit:G)' 'crit=used>95' 'warn=used>90%'
Result (running manually from commandline): 
OK All 1 drive(s) are ok|'C:\ used'=63.49453G;72.00033;76.00035;0;80.00037 'C:\ used %'=79%;90;95;0;100   (which is ok)

Result when the same command is executed by mod_gearman (extracted from status-file or as observed in thruk):
OK All 1 drive(s) are ok|'C:\\ used'=63.49453G;72.00033;76.00035;0;80.00037 'C:\\ used %'=79%;90;95;0;100   (which is not ok)

When using a normal slash insted of a backslash, the results are ok, no duplication takes place.

I took a look at the sources of mod_gearman (common/utils.c) and found function "gm_escape_newlines". Inside this function backslashes are duplicated. Could this eventually be the source of my problem?
...
        /* escape backslashes */
        if(tmpbuf[x]=='\\'){
            newbuf[y++]='\\';
            newbuf[y++]='\\';
        }
...

Any ideas are appreciated!

**Comment by sni** [comment]
maybe thats not neccessary anymore for naemon

**Comment by anfoe1111** [comment]
Could you provide a fix or should I try to comment the corresponding code-lines?

**Comment by sni** [comment]
right now i don't have the time to investigate possible side effects of removing the double slash. So i'd be glad if you try that yourself and send a pull request if you found a solution.

**Comment by anfoe1111** [comment]
After commenting the related lines and rebuilding mod_gearman, everything works fine so far. As we are testing at the moment, I'll keep you informed if we observe any side-effects. Thanks for your help.

**Comment by anfoe1111** [comment]
I'm not quite sure that I understand all of the programming logic of mod_gearman. I tested two variants for a pull-request, both work fine for our distributed naemon-config.

Here is what I tried so far:

**Variant 1:**
I put comments on the "escape backslashes" section of function "gm_escape_newlines" in common/utils.c. This function is called by function "extract_check_results" called by procedure "run_check" called by procedure "execute_safe_command" called by the worker-process.
I'm not sure if this change is compatible to Nagios 3.X or 4.X-configurations, because the worker-binary created is used for nagios (3.X/4.X) and for naemon as well. 
Inside the same function newlines are escaped as well. For neamon-environments (#ifdef NAEMON), these newlines are removed later in the neb-module, it seems they are not necessary for naemon.
--> Result: everything works fine, backslahes do not appear on the central server (= dupserver) and on the remote server.

**Variant 2:**
I did not change function "gm_escape_newlines", instead I changed the neb-module and substitued two backslashes by one backslash in procedures "handle_perfdata", where the escaped newlines are un-escaped. Advantage: This can be surrounded by a "#ifdef USENAEMON", to make the change naemon-specific.
--> Result: everything works fine, backslahes do not appear on the central server (= dupserver) and on the remote server.

I would prefer variant #2 for the pull-request, what do you think?

**Comment by sni** [comment]
Should be fixed now. Thanks.

Yes, removing all the unnecessary escaping for naemon would be a good thing. But i doubt this is possible without breaking backwards compatibility.
